version: '2'

volumes:

services:
  nginx:
    image: nginx:1.13.6
  volumes:
    - ./formaster.conf:/etc/nginx/conf.d/formaster.conf
  ports:
    - "8080:80"
  environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
  links:
    - django
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/formaster.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ForMaster